name: Deploy to GitHub Pages

on:
  push:
    branches: [dev] # 根据你的主分支名调整，如 master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 👇 关键：安装 pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.bd2_pro }}
          publish_dir: ./dist # 构建输出目录
